import { useEffect, useRef, useState } from 'react';
import type { DrawAndGuessState, PublicPlayer } from '../types/game';

export function DrawAndGuessGame({ game, me, disabled = false, onAction }: { game: DrawAndGuessState; me?: PublicPlayer; disabled?: boolean; onAction: (action: { type: 'draw-stroke'; stroke: { x: number; y: number; toX: number; toY: number } } | { type: 'guess'; guess: string }) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const previous = useRef<{ x: number; y: number } | null>(null); const [guess, setGuess] = useState(''); const [, setClock] = useState(0);
  const artist = me?.seat === game.artistSeat;
  useEffect(() => { const timer = window.setInterval(() => setClock((value) => value + 1), 1_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = '#fbbf24'; ctx.lineWidth = 5; ctx.lineCap = 'round'; game.strokes.forEach((stroke) => { ctx.beginPath(); ctx.moveTo(stroke.x * canvas.width, stroke.y * canvas.height); ctx.lineTo(stroke.toX * canvas.width, stroke.toY * canvas.height); ctx.stroke(); }); }, [game.strokes]);
  const point = (event: React.PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - rect.left) / rect.width, y: (event.clientY - rect.top) / rect.height }; };
  const draw = (event: React.PointerEvent<HTMLCanvasElement>) => { if (disabled || !artist || !previous.current) return; const next = point(event); onAction({ type: 'draw-stroke', stroke: { ...previous.current, toX: next.x, toY: next.y } }); previous.current = next; };
  const seconds = game.endsAt ? Math.max(0, Math.ceil((game.endsAt - Date.now()) / 1000)) : 0;
  return <section className="mx-auto w-full max-w-xl rounded-3xl border border-white/10 bg-white/5 p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-amber-300">{artist ? 'Your prompt' : 'Guess the drawing'}</p><h2 className="mt-1 text-3xl font-black">{artist ? game.prompt : `${game.category} · ${'•'.repeat(game.wordLength)}`}</h2></div><span className="rounded-full bg-zinc-900 px-3 py-2 font-bold">{seconds}s</span></div><canvas ref={canvasRef} width="700" height="500" onPointerDown={(event) => { if (!disabled && artist) { previous.current = point(event); event.currentTarget.setPointerCapture(event.pointerId); } }} onPointerMove={draw} onPointerUp={() => { previous.current = null; }} className={`mt-5 aspect-[7/5] w-full rounded-2xl border border-white/10 bg-zinc-950 touch-none ${artist && !disabled ? 'cursor-crosshair' : ''}`} aria-label="Shared drawing canvas" />{disabled ? <p className="mt-4 text-center text-sm text-zinc-400">Share the room code above to start playing.</p> : artist ? <p className="mt-4 text-center text-sm text-zinc-400">Draw the prompt. Your opponent is guessing.</p> : <form onSubmit={(event) => { event.preventDefault(); if (guess.trim()) { onAction({ type: 'guess', guess }); setGuess(''); } }} className="mt-4 flex gap-2"><input value={guess} onChange={(event) => setGuess(event.target.value)} placeholder="Enter your guess" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-zinc-900 px-4 py-3 outline-none focus:border-amber-300" /><button className="rounded-xl bg-amber-300 px-5 font-bold text-zinc-950">Guess</button></form>}</section>;
}
